In [1]:
import numpy as np

In [2]:
ls = [[1,2,5,6,7,8,9]]
arr = np.array(ls)
print(type(ls))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [3]:
arr.shape

(1, 7)

In [6]:
l = [[1,2.,3],[4,5,6],[7,8,9]]
arr = np.array(l)
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [7]:
arr.dtype

dtype('float64')

In [8]:
np.array([1,2,3+4j])

array([1.+0.j, 2.+0.j, 3.+4.j])

In [9]:
np.array([1,2,3.0], dtype='int32')

array([1, 2, 3], dtype=int32)

In [14]:
np.array([1,2,3+1j], dtype='str')

array(['1', '2', '(3+1j)'], dtype='<U6')

In [19]:
#create a 2D array
arr = np.array([[1,2,3],[4,5,6],[7,8,np.nan]])
print(arr)
print(arr.dtype)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. nan]]
float64


In [26]:
# list(range(1.5, 11.5))
print(np.arange(1.5, 11.5, 0.2))

[ 1.5  1.7  1.9  2.1  2.3  2.5  2.7  2.9  3.1  3.3  3.5  3.7  3.9  4.1
  4.3  4.5  4.7  4.9  5.1  5.3  5.5  5.7  5.9  6.1  6.3  6.5  6.7  6.9
  7.1  7.3  7.5  7.7  7.9  8.1  8.3  8.5  8.7  8.9  9.1  9.3  9.5  9.7
  9.9 10.1 10.3 10.5 10.7 10.9 11.1 11.3]


In [28]:
arr = np.array(([1,2,3],[4,5,6]))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
arr.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [36]:
# create 3D array
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [37]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [42]:
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [43]:
np.full(10,7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [44]:
np.full([2,3],[7,8,9])

array([[7, 8, 9],
       [7, 8, 9]])

In [45]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [76]:
np.random.randint(1,10)

7

In [73]:
np.random.rand(1,10,5)

array([[[0.41752865, 0.77918473, 0.69113127, 0.96995482, 0.19225312],
        [0.44392722, 0.10932835, 0.92689001, 0.71676583, 0.0752343 ],
        [0.18453567, 0.58771469, 0.18224064, 0.93495346, 0.45989608],
        [0.3366774 , 0.29661628, 0.49651013, 0.58947554, 0.69887173],
        [0.15822618, 0.66258253, 0.98791215, 0.47365576, 0.033492  ],
        [0.81155427, 0.51559014, 0.08832498, 0.45854668, 0.90788141],
        [0.97806368, 0.70272175, 0.72194051, 0.61429889, 0.07439367],
        [0.01528795, 0.56280244, 0.67149506, 0.67443859, 0.56336415],
        [0.13664132, 0.97500862, 0.73918767, 0.59609741, 0.28497915],
        [0.6607041 , 0.29060081, 0.12518434, 0.9760203 , 0.78282502]]])

In [77]:
np.random.randn(5)

array([-0.30943922, -0.05821889, -0.98165004,  0.0016816 , -0.33146078])

In [82]:
np.linspace(1,10,5,dtype=int)

array([ 1,  3,  5,  7, 10])

In [85]:
np.linspace(2,10,retstep=True)

(array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
         2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
         3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
         4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
         5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
         6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
         6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
         7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
         8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
         9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ]),
 np.float64(0.16326530612244897))

In [87]:
arr = np.arange(1,11).reshape([2,5])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Copy And View

In [88]:
new_arr = arr.reshape
new_arr

<function ndarray.reshape(*shape, order='C', copy=None)>

In [89]:
arr[0][0] = 100
arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [90]:
new_arr_copy = arr.copy()
new_arr_copy

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])